server:
  port: 8084
  servlet:
    context-path: /demo-executor

faya-job:
  zookeeperServer: 192.168.88.130:2181
  registerPath: /job-register
  demo-executor:
     server: 127.0.0.1
     port: 8072
     weight: 1
     name: DEMO
     mainClass: com.fayayo.job.demo.executor.DemoEngine