server:
  port: 8083
  servlet:
    context-path: /demo-executor

faya-job:
  register:
    server: 192.168.88.130:2181
    path: /job-register
    open: false
  demo-executor:
     server: 192.168.88.130
     port: 8070
     weight: 1
     name: DEMO
     mainClass: com.fayayo.job.demo.executor.DemoEngine

