server:
  port: 8083
  servlet:
    context-path: /demo-executor

faya-job:
  register:
    server: 192.168.88.130:2181
    path: /job-register
    open: false
  demo-executor:
     server: 127.0.0.1
     port: 8073
     weight: 1
     name: DEMO
     mainClass: com.fayayo.job.demo.executor.DemoEngine
     logPath: D:/app/workspace/logs/faya_job/datax-executor