server:
  port: 8083
  servlet:
    context-path: /datax-executor

faya-job:
  zookeeperServer: 192.168.88.130:2181
  #zookeeperServer: 192.168.76.139:2181
  registerPath: /job-register
  datax-executor:
     server: 127.0.0.1
     port: 8070
     weight: 1
     name: datax
     mainClass: com.fayayo.job.datax.executor.DataxEngine
  datax:
     config: /home/faya/config



