server:
  port: 8083
  servlet:
    context-path: /datax-executor

faya-job:
  zookeeperServer: 192.168.88.130:2181
  registerPath: /job-register
  datax-executor:
     server: 192.168.88.130
     port: 8070
     weight: 1
     name: DATAX
     mainClass: com.fayayo.job.datax.executor.DataxEngine
     logPath: /home/faya/datax/log
  datax:
      config: /home/faya/job_config
#  ftp-server:
#     ip: 192.168.88.129
#     username: root
#     password: root123
#     serverPath: /root/ftpdata/job_config


