spring:
  datasource:
    url: jdbc:mysql://localhost:3306/faya_job_manager?user=root&password=root123&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: GMT+8
server:
  port: 8081
  servlet:
    context-path: /manager

faya-job:
  register:
    server: 192.168.88.129:2181
    path: /job-register
    open: true
  upload:
    tempPath: /upload
